f = open("pythonessay.txt", "w")
f.write("I like Python because it's very interesting.")
f = open("pythonessay.txt", "a")
f.write("\nI plan to learn data visualization.")
f.write("\nI want to work in the field of data science.")
f.write("\nI plan to make a better world for the future generation.")
f = open("pythonessay.txt", "r")
f.close()